version: 2
ethernets:
  ens3:
    addresses:
      - 192.168.0.37/24
    gateway4: 192.168.0.1
    nameservers:
        search: [planetexpress.com.au]
        addresses: [192.168.0.14, 8.8.4.4]