#cloud-config
# Hostname management
hostname: ubuntu-test
manage_etc_hosts: true
preserve_hostname: false
 
# Setup Users with ssh keys so that I can log in into new machine
users:
    - name: johannlo
      groups: ['wheel','sudo']
      shell: /bin/bash
      sudo: ALL=(ALL) ALL
      lock_passwd: False
      passwd: $1$SaltSalt$PGO6XOjxBrQx1.Ufa16Nz0
      ssh-authorized-keys:
        - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQD9gVPVPCSpvF+qYBQOUPGnXwzmXwdztLDoiwNu5eRAsbU75CCRN9JMb0Rv3/ZQ25rvWs2tHjdaGps79Nv80/IATibRIUtYvqbhj8nIJY+M6N//3vwiOA48PM1TWls88f/dfaHBKbCsX9ZZCtcSMlmSxOzyPd86mG65z3SyPhYPQlOQjlxg5gW9wp/eJohovZChoH/QvfQEXHcctnfPKErRn4bHWPz0XlovCwtaUCKJa6D3yNJ/HeqD/D3ib8ko8hR1jjTuvPuiQo+147PEQmD81dRcWJGwePsMs18EXo2wtYVqZgYThfxrTyK9wRNvBtdQwXLDdPJlYJhTGrUwjDwL johannlo@tiny
    - name: cisco
      shell: /bin/bash
      lock_passwd: False
      passwd: $1$SaltSalt$rk84ScI0zorI4msU7w79V.
      
# Configure where output will go
output:
  all: ">> /var/log/cloud-init.log"
 
# configure interaction with ssh server
ssh_genkeytypes: ['ed25519', 'rsa']
  
# set timezone for VM
timezone: Australia/Melbourne
 
# Apply networking
runcmd:
# - netplan apply
 - apt-get -y remove cloud-init



